[al_7050_t7451_plate_l_75_100_a]
name = "al_7050_t7451_plate_l_75_100_a"
family = "Aluminium"
alloy = 7050
temper = "T7451"
basis = "A"
form = "Plate"
tlower = 75.0
tupper = 100.0
orientation = "L"
spec = "AIMS 03-02-019"
description = "7050 T7451, unclad plate, high toughness (Material according to AIMS 03-02-019). Ramberg-Osgood coefficients from HSB 12522-01 B/2001, 7050T7451, 12.7<t<100, L direction"
source = "HSB 12512-72, A/2007"
E = 71000.0
Ec = 75000.0
nu = 0.33
rho = 2.82
Ftu = 485.0
Fty = 425.0
Fcy = 415.0
Fsu = 305.0
Fbru15 = 770.0
Fbru20 = 985.0
Fbry15 = 640.0
Fbry20 = 780.0
nro_t = 19.0
nro_c = 18.0

[al_7050_t7451_plate_lt_75_100_a]
name = "al_7050_t7451_plate_lt_75_100_a"
family = "Aluminium"
alloy = 7050
temper = "T7451"
basis = "A"
form = "Plate"
tlower = 75.0
tupper = 100.0
orientation = "LT"
spec = "AIMS 03-02-019"
description = "7050 T7451, unclad plate, high toughness (Material according to AIMS 03-02-019). Ramberg-Osgood coefficients from HSB 12522-01 B/2001, 7050T7451, 12.7<t<100, LT direction"
source = "HSB 12512-72, A/2007"
E = 71000.0
Ec = 75000.0
nu = 0.33
rho = 2.82
Ftu = 490.0
Fty = 425.0
Fcy = 440.0
Fsu = 305.0
Fbru15 = 770.0
Fbru20 = 985.0
Fbry15 = 640.0
Fbry20 = 780.0
nro_t = 19.0
nro_c = 22.0

[al_7050_t7451_plate_st_75_100_a]
name = "al_7050_t7451_plate_st_75_100_a"
family = "Aluminium"
alloy = 7050
temper = "T7451"
basis = "A"
form = "Plate"
tlower = 75.0
tupper = 100.0
orientation = "ST"
spec = "AIMS 03-02-019"
description = "7050 T7451, unclad plate, high toughness (Material according to AIMS 03-02-019). Ramberg-Osgood coefficients from HSB 12522-01 B/2001, 7050T7451, 12.7<t<100, ST direction"
source = "HSB 12512-72, A/2007"
E = 71000.0
Ec = 75000.0
nu = 0.33
rho = 2.82
Ftu = 475.0
Fty = 405.0
Fcy = 435.0
Fsu = 305.0
Fbru15 = 770.0
Fbru20 = 985.0
Fbry15 = 640.0
Fbry20 = 780.0
nro_t = 10.0
nro_c = 16.0

[al_7050_t7451_plate_l_75_100_b]
name = "al_7050_t7451_plate_l_75_100_b"
family = "Aluminium"
alloy = 7050
temper = "T7451"
basis = "B"
form = "Plate"
tlower = 75.0
tupper = 100.0
orientation = "L"
spec = "AIMS 03-02-019"
description = "7050 T7451, unclad plate, high toughness (Material according to AIMS 03-02-019). Ramberg-Osgood coefficients from HSB 12522-01 B/2001, 7050T7451, 12.7<t<100, L direction"
source = "HSB 12512-72, A/2007"
E = 71000.0
Ec = 75000.0
nu = 0.33
rho = 2.82
Ftu = 495.0
Fty = 450.0
Fcy = 435.0
Fsu = 325.0
Fbru15 = 805.0
Fbru20 = 1035.0
Fbry15 = 670.0
Fbry20 = 820.0
nro_t = 19.0
nro_c = 18.0

[al_7050_t7451_plate_lt_75_100_b]
name = "al_7050_t7451_plate_lt_75_100_b"
family = "Aluminium"
alloy = 7050
temper = "T7451"
basis = "B"
form = "Plate"
tlower = 75.0
tupper = 100.0
orientation = "LT"
spec = "AIMS 03-02-019"
description = "7050 T7451, unclad plate, high toughness (Material according to AIMS 03-02-019). Ramberg-Osgood coefficients from HSB 12522-01 B/2001, 7050T7451, 12.7<t<100, LT direction"
source = "HSB 12512-72, A/2007"
E = 71000.0
Ec = 75000.0
nu = 0.33
rho = 2.82
Ftu = 510.0
Fty = 450.0
Fcy = 460.0
Fsu = 325.0
Fbru15 = 805.0
Fbru20 = 1035.0
Fbry15 = 670.0
Fbry20 = 820.0
nro_t = 19.0
nro_c = 22.0

[al_7050_t7451_plate_st_75_100_b]
name = "al_7050_t7451_plate_st_75_100_b"
family = "Aluminium"
alloy = 7050
temper = "T7451"
basis = "B"
form = "Plate"
tlower = 75.0
tupper = 100.0
orientation = "ST"
spec = "AIMS 03-02-019"
description = "7050 T7451, unclad plate, high toughness (Material according to AIMS 03-02-019). Ramberg-Osgood coefficients from HSB 12522-01 B/2001, 7050T7451, 12.7<t<100, ST direction"
source = "HSB 12512-72, A/2007"
E = 71000.0
Ec = 75000.0
nu = 0.33
rho = 2.82
Ftu = 485.0
Fty = 420.0
Fcy = 455.0
Fsu = 325.0
Fbru15 = 805.0
Fbru20 = 1035.0
Fbry15 = 670.0
Fbry20 = 820.0
nro_t = 10.0
nro_c = 16.0

[al_7050_t7451_plate_l_100_125_a]
name = "al_7050_t7451_plate_l_100_125_a"
family = "Aluminium"
alloy = 7050
temper = "T7451"
basis = "A"
form = "Plate"
tlower = 100.0
tupper = 125.0
orientation = "L"
spec = "AIMS 03-02-019"
description = "7050 T7451, unclad plate, high toughness (Material according to AIMS 03-02-019)"
source = "HSB 12512-72, A/2007"
E = 71000.0
Ec = 75000.0
nu = 0.33
rho = 2.82
Ftu = 485.0
Fty = 425.0
Fcy = 415.0
Fsu = 305.0
Fbru15 = 770.0
Fbru20 = 985.0
Fbry15 = 640.0
Fbry20 = 770.0

[al_7050_t7451_plate_lt_100_125_a]
name = "al_7050_t7451_plate_lt_100_125_a"
family = "Aluminium"
alloy = 7050
temper = "T7451"
basis = "A"
form = "Plate"
tlower = 100.0
tupper = 125.0
orientation = "LT"
spec = "AIMS 03-02-019"
description = "7050 T7451, unclad plate, high toughness (Material according to AIMS 03-02-019)"
source = "HSB 12512-72, A/2007"
E = 71000.0
Ec = 75000.0
nu = 0.33
rho = 2.82
Ftu = 490.0
Fty = 425.0
Fcy = 440.0
Fsu = 305.0
Fbru15 = 770.0
Fbru20 = 985.0
Fbry15 = 640.0
Fbry20 = 770.0

[al_7050_t7451_plate_st_100_125_a]
name = "al_7050_t7451_plate_st_100_125_a"
family = "Aluminium"
alloy = 7050
temper = "T7451"
basis = "A"
form = "Plate"
tlower = 100.0
tupper = 125.0
orientation = "ST"
spec = "AIMS 03-02-019"
description = "7050 T7451, unclad plate, high toughness (Material according to AIMS 03-02-019)"
source = "HSB 12512-72, A/2007"
E = 71000.0
Ec = 75000.0
nu = 0.33
rho = 2.82
Ftu = 470.0
Fty = 400.0
Fcy = 435.0
Fsu = 305.0
Fbru15 = 770.0
Fbru20 = 985.0
Fbry15 = 640.0
Fbry20 = 770.0

[al_7050_t7451_plate_l_100_125_b]
name = "al_7050_t7451_plate_l_100_125_b"
family = "Aluminium"
alloy = 7050
temper = "T7451"
basis = "B"
form = "Plate"
tlower = 100.0
tupper = 125.0
orientation = "L"
spec = "AIMS 03-02-019"
description = "7050 T7451, unclad plate, high toughness (Material according to AIMS 03-02-019)"
source = "HSB 12512-72, A/2007"
E = 71000.0
Ec = 75000.0
nu = 0.33
rho = 2.82
Ftu = 495.0
Fty = 440.0
Fcy = 425.0
Fsu = 315.0
Fbru15 = 790.0
Fbru20 = 1015.0
Fbry15 = 670.0
Fbry20 = 820.0

[al_7050_t7451_plate_lt_100_125_b]
name = "al_7050_t7451_plate_lt_100_125_b"
family = "Aluminium"
alloy = 7050
temper = "T7451"
basis = "B"
form = "Plate"
tlower = 100.0
tupper = 125.0
orientation = "LT"
spec = "AIMS 03-02-019"
description = "7050 T7451, unclad plate, high toughness (Material according to AIMS 03-02-019)"
source = "HSB 12512-72, A/2007"
E = 71000.0
Ec = 75000.0
nu = 0.33
rho = 2.82
Ftu = 505.0
Fty = 450.0
Fcy = 480.0
Fsu = 315.0
Fbru15 = 790.0
Fbru20 = 1015.0
Fbry15 = 670.0
Fbry20 = 820.0

[al_7050_t7451_plate_st_100_125_b]
name = "al_7050_t7451_plate_st_100_125_b"
family = "Aluminium"
alloy = 7050
temper = "T7451"
basis = "B"
form = "Plate"
tlower = 100.0
tupper = 125.0
orientation = "ST"
spec = "AIMS 03-02-019"
description = "7050 T7451, unclad plate, high toughness (Material according to AIMS 03-02-019)"
source = "HSB 12512-72, A/2007"
E = 71000.0
Ec = 75000.0
nu = 0.33
rho = 2.82
Ftu = 485.0
Fty = 420.0
Fcy = 455.0
Fsu = 315.0
Fbru15 = 790.0
Fbru20 = 1015.0
Fbry15 = 670.0
Fbry20 = 820.0

[al_7475_t761_cladsheet_l_1.0_1.6_s]
name = "al_7475_t761_cladsheet_l_1.0_1.6_s"
family = "Aluminium"
alloy = 7475
temper = "T761"
basis = "S"
form = "Clad Sheet"
tlower = 1.0
tupper = 1.6
orientation = "L"
spec = "AIMS 03-04-029"
description = "7475-T761, alclad sheet, special surface quality (Ref.: MIL-HDBK 5H, AIMS 03-04-029)"
source = "HSB 12512-74 B/2001"
E = 69000.0
E_secondary = 63400.0
Ec = 72400.0
Ec_secondary = 64800.0
nu = 0.35
rho = 2.8
Ftu = 455.0
Fty = 385.0
Fcy = 380.0
Fsu = 285.0
Fbru15 = 715.0
Fbru20 = 915.0
Fbry15 = 570.0
Fbry20 = 670.0

[al_7475_t761_cladsheet_lt_1.0_1.6_s]
name = "al_7475_t761_cladsheet_lt_1.0_1.6_s"
family = "Aluminium"
alloy = 7475
temper = "T761"
basis = "S"
form = "Clad Sheet"
tlower = 1.0
tupper = 1.6
orientation = "LT"
spec = "AIMS 03-04-029"
description = "7475-T761, alclad sheet, special surface quality (Ref.: MIL-HDBK 5H, AIMS 03-04-029)"
source = "HSB 12512-74 B/2001"
E = 69000.0
E_secondary = 63400.0
Ec = 72400.0
Ec_secondary = 64800.0
nu = 0.35
rho = 2.8
Ftu = 455.0
Fty = 380.0
Fcy = 400.0
Fsu = 285.0
Fbru15 = 715.0
Fbru20 = 915.0
Fbry15 = 570.0
Fbry20 = 670.0

[al_7475_t761_cladsheet_l_1.6_4.7_a]
name = "al_7475_t761_cladsheet_l_1.6_4.7_a"
family = "Aluminium"
alloy = 7475
temper = "T761"
basis = "A"
form = "Clad Sheet"
tlower = 1.6
tupper = 4.7
orientation = "L"
spec = "AIMS 03-04-029"
description = "7475-T761, alclad sheet, special surface quality (Ref.: MIL-HDBK 5H, AIMS 03-04-029)"
source = "HSB 12512-74 B/2001"
E = 69000.0
E_secondary = 64800.0
Ec = 72400.0
Ec_secondary = 66900.0
nu = 0.35
rho = 2.8
Ftu = 460.0
Fty = 400.0
Fcy = 385.0
Fsu = 275.0
Fbru15 = 730.0
Fbru20 = 935.0
Fbry15 = 595.0
Fbry20 = 695.0

[al_7475_t761_cladsheet_lt_1.6_4.7_a]
name = "al_7475_t761_cladsheet_lt_1.6_4.7_a"
family = "Aluminium"
alloy = 7475
temper = "T761"
basis = "A"
form = "Clad Sheet"
tlower = 1.6
tupper = 4.7
orientation = "LT"
spec = "AIMS 03-04-029"
description = "7475-T761, alclad sheet, special surface quality (Ref.: MIL-HDBK 5H, AIMS 03-04-029)"
source = "HSB 12512-74 B/2001"
E = 69000.0
E_secondary = 64800.0
Ec = 72400.0
Ec_secondary = 66900.0
nu = 0.35
rho = 2.8
Ftu = 470.0
Fty = 395.0
Fcy = 405.0
Fsu = 275.0
Fbru15 = 730.0
Fbru20 = 935.0
Fbry15 = 595.0
Fbry20 = 695.0

[al_7475_t761_cladsheet_l_1.6_4.7_b]
name = "al_7475_t761_cladsheet_l_1.6_4.7_b"
family = "Aluminium"
alloy = 7475
temper = "T761"
basis = "B"
form = "Clad Sheet"
tlower = 1.6
tupper = 4.7
orientation = "L"
spec = "AIMS 03-04-029"
description = "7475-T761, alclad sheet, special surface quality (Ref.: MIL-HDBK 5H, AIMS 03-04-029)"
source = "HSB 12512-74 B/2001"
E = 69000.0
E_secondary = 64800.0
Ec = 72400.0
Ec_secondary = 66900.0
nu = 0.35
rho = 2.8
Ftu = 480.0
Fty = 420.0
Fcy = 405.0
Fsu = 285.0
Fbru15 = 760.0
Fbru20 = 965.0
Fbry15 = 620.0
Fbry20 = 730.0

[al_7475_t761_cladsheet_lt_1.6_4.7_b]
name = "al_7475_t761_cladsheet_lt_1.6_4.7_b"
family = "Aluminium"
alloy = 7475
temper = "T761"
basis = "B"
form = "Clad Sheet"
tlower = 1.6
tupper = 4.7
orientation = "LT"
spec = "AIMS 03-04-029"
description = "7475-T761, alclad sheet, special surface quality (Ref.: MIL-HDBK 5H, AIMS 03-04-029)"
source = "HSB 12512-74 B/2001"
E = 69000.0
E_secondary = 64800.0
Ec = 72400.0
Ec_secondary = 66900.0
nu = 0.35
rho = 2.8
Ftu = 480.0
Fty = 415.0
Fcy = 430.0
Fsu = 285.0
Fbru15 = 760.0
Fbru20 = 965.0
Fbry15 = 620.0
Fbry20 = 730.0

[al_7475_t761_cladsheet_l_4.7_6.0_a]
name = "al_7475_t761_cladsheet_l_4.7_6.0_a"
family = "Aluminium"
alloy = 7475
temper = "T761"
basis = "A"
form = "Clad Sheet"
tlower = 4.7
tupper = 6.0
orientation = "L"
spec = "AIMS 03-04-029"
description = "7475-T761, alclad sheet, special surface quality (Ref.: MIL-HDBK 5H, AIMS 03-04-029)"
source = "HSB 12512-74 B/2001"
E = 69000.0
E_secondary = 66900.0
Ec = 72400.0
Ec_secondary = 69000.0
nu = 0.35
rho = 2.8
Ftu = 470.0
Fty = 405.0
Fcy = 400.0
Fsu = 275.0
Fbru15 = 745.0
Fbru20 = 950.0
Fbry15 = 620.0
Fbry20 = 730.0

[al_7475_t761_cladsheet_lt_4.7_6.0_a]
name = "al_7475_t761_cladsheet_lt_4.7_6.0_a"
family = "Aluminium"
alloy = 7475
temper = "T761"
basis = "A"
form = "Clad Sheet"
tlower = 4.7
tupper = 6.0
orientation = "LT"
spec = "AIMS 03-04-029"
description = "7475-T761, alclad sheet, special surface quality (Ref.: MIL-HDBK 5H, AIMS 03-04-029)"
source = "HSB 12512-74 B/2001"
E = 69000.0
E_secondary = 66900.0
Ec = 72400.0
Ec_secondary = 69000.0
nu = 0.35
rho = 2.8
Ftu = 480.0
Fty = 415.0
Fcy = 420.0
Fsu = 275.0
Fbru15 = 745.0
Fbru20 = 950.0
Fbry15 = 620.0
Fbry20 = 730.0

[al_7475_t761_cladsheet_l_4.7_6.0_b]
name = "al_7475_t761_cladsheet_l_4.7_6.0_b"
family = "Aluminium"
alloy = 7475
temper = "T761"
basis = "B"
form = "Clad Sheet"
tlower = 4.7
tupper = 6.0
orientation = "L"
spec = "AIMS 03-04-029"
description = "7475-T761, alclad sheet, special surface quality (Ref.: MIL-HDBK 5H, AIMS 03-04-029)"
source = "HSB 12512-74 B/2001"
E = 69000.0
E_secondary = 66900.0
Ec = 72400.0
Ec_secondary = 69000.0
nu = 0.35
rho = 2.8
Ftu = 490.0
Fty = 435.0
Fcy = 415.0
Fsu = 285.0
Fbru15 = 765.0
Fbru20 = 980.0
Fbry15 = 640.0
Fbry20 = 760.0

[al_7475_t761_cladsheet_lt_4.7_6.0_b]
name = "al_7475_t761_cladsheet_lt_4.7_6.0_b"
family = "Aluminium"
alloy = 7475
temper = "T761"
basis = "B"
form = "Clad Sheet"
tlower = 4.7
tupper = 6.0
orientation = "LT"
spec = "AIMS 03-04-029"
description = "7475-T761, alclad sheet, special surface quality (Ref.: MIL-HDBK 5H, AIMS 03-04-029)"
source = "HSB 12512-74 B/2001"
E = 69000.0
E_secondary = 66900.0
Ec = 72400.0
Ec_secondary = 69000.0
nu = 0.35
rho = 2.8
Ftu = 495.0
Fty = 430.0
Fcy = 435.0
Fsu = 285.0
Fbru15 = 765.0
Fbru20 = 980.0
Fbry15 = 640.0
Fbry20 = 760.0

[bz_c17200_bar_l_2.5_3.0_a]
name = "bz_c17200_bar_l_2.5_3.0_a"
family = "Bronze"
alloy = "C17200"
temper = "TH04"
basis = "A"
form = "Bar"
tlower = 63.5
tupper = 76.2
orientation = "L"
spec = "AMS 4534"
description = "C17200 Copper Beryllium Rod and Bar"
source = "MMPDS-06"
E = 127557.5
Ec = 128936.5
nu = 0.27
G = 50333.5
rho = 8.24864
Ftu = 1185.94
Fty = 999.775
Fcy = 1020.46
Fsu = 648.13
Fbru15 = 1592.745
Fbru20 = 2020.235
Fbry15 = 1427.265
Fbry20 = 1551.375

[bz_c17200_bar_st_2.5_3.0_a]
name = "bz_c17200_bar_st_2.5_3.0_a"
family = "Bronze"
alloy = "C17200"
temper = "TH04"
basis = "A"
form = "Bar"
tlower = 63.5
tupper = 76.2
orientation = "ST"
spec = "AMS 4534"
description = "C17200 Copper Beryllium Rod and Bar"
source = "MMPDS-06"
E = 127557.5
Ec = 128936.5
nu = 0.27
G = 50333.5
rho = 8.24864
Ftu = 1151.465
Fty = 965.3
Fcy = 1061.83
Fsu = 648.13
Fbru15 = 1592.745
Fbru20 = 2020.235
Fbry15 = 1427.265
Fbry20 = 1551.375

[bz_c17200_bar_l_2.5_3.0_b]
name = "bz_c17200_bar_l_2.5_3.0_b"
family = "Bronze"
alloy = "C17200"
temper = "TH04"
basis = "B"
form = "Bar"
tlower = 63.5
tupper = 76.2
orientation = "L"
spec = "AMS 4534"
description = "C17200 Copper Beryllium Rod and Bar"
source = "MMPDS-06"
E = 127557.5
Ec = 128936.5
nu = 0.27
G = 50333.5
rho = 8.24864
Ftu = 1227.31
Fty = 1048.04
Fcy = 1068.725
Fsu = 661.92
Fbru15 = 1647.905
Fbru20 = 2089.185
Fbry15 = 1496.215
Fbry20 = 1627.22

[bz_c17200_bar_st_2.5_3.0_b]
name = "bz_c17200_bar_st_2.5_3.0_b"
family = "Bronze"
alloy = "C17200"
temper = "TH04"
basis = "B"
form = "Bar"
tlower = 63.5
tupper = 76.2
orientation = "ST"
spec = "AMS 4534"
description = "C17200 Copper Beryllium Rod and Bar"
source = "MMPDS-06"
E = 127557.5
Ec = 128936.5
nu = 0.27
G = 50333.5
rho = 8.24864
Ftu = 1192.835
Fty = 1013.565
Fcy = 1116.99
Fsu = 661.92
Fbru15 = 1647.905
Fbru20 = 2089.185
Fbry15 = 1496.215
Fbry20 = 1627.22

[al_7070_t7451_plate_l_30_50_b]
name = "al_7070_t7451_plate_l_30_50_b"
family = "Aluminium"
alloy = 7050
temper = "T7451"
basis = "B"
form = "Plate"
tlower = 30.0
tupper = 50.0
orientation = "L"
spec = "AIMS 03-02-022"
description = "7050 T7451, unclad plate, standard quality (material according to EN3982 and AIMS 03-02-022). A and B values in agreement with MMPDS-03"
source = "HSB 12512-73 C/2007"
E = 71000.0
Ec = 73000.0
nu = 0.33
rho = 2.82
Ftu = 525.0
Fty = 455.0
Fcy = 440.0
Fsu = 305.0
Fbru15 = 770.0
Fbru20 = 1005.0
Fbry15 = 635.0
Fbry20 = 735.0
A = 0.1

[al_2024_t3_cladsheet_lt_1.6_3.2_b]
name = "al_2024_t3_cladsheet_lt_1.6_3.2_b"
family = "Aluminium"
alloy = 2024
temper = "T351"
basis = "B"
form = "Clad Sheet"
tlower = 1.6
tupper = 2.3
orientation = "LT"
spec = "AIMS 03-04-009, AIMS 03-04-011, AIMS 03-04-013, AIMS 03-04-014"
source = "HSB 12512-20 C/2006"
E = 72400.0
E_secondary = 69000.0
Ec = 73800.0
Ec_secondary = 70300.0
nu = 0.33
rho = 2.8
Ftu = 430.0
Fty = 290.0
Fcy = 310.0
Fsu = 270.0
Fbru15 = 705.0
Fbru20 = 875.0
Fbry15 = 505.0
Fbry20 = 605.0
A = 0.15

[ti_64_ab_plate_l_6_10_b]
name = "ti_64_ab_plate_l_6_10_b"
family = "Titanium"
alloy = "Ti6AL4V"
basis = "B"
form = "Plate"
tlower = 6.0
tupper = 10.0
orientation = "L"
spec = "AIMS 03-18-001, AIMS 03-18-004, AIMS 03-18-006"
description = "Ti6Al4V, a-ÃŸ-annealed, sheet/plate (Material according to AIMS 03-18-004 and  AIMS 03-18-001/006, A- and B-value are in accordance with MMPDS-04, AMS 4911)"
source = "HSB 12571-03, D/2009"
E = 110300.0
Ec = 113100.0
rho = 4.43
Ftu = 930.0
Fty = 860.0
Fcy = 890.0
Fsu = 580.0
Fbru15 = 1475.0
Fbru20 = 1905.0
Fbry15 = 1235.0
Fbry20 = 1460.0
A = 0.08

